/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panelview;

import applicationview.BukuPedomanKakSuh;
import applicationview.BukuPedomanManajemen;
import applicationview.BukuPedomanProgress;
import applicationview.FormProgress;
import java.awt.Color;


/**
 *
 * @author raja
 */
public class menuPencatatan extends javax.swing.JPanel {
   


    public menuPencatatan() {
        initComponents();
 
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMain = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btn_Mulai = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panel_manajemen = new javax.swing.JPanel();
        btn_manajemen = new javax.swing.JLabel();
        panel_pencatatan = new javax.swing.JPanel();
        btn_pencatatan = new javax.swing.JLabel();
        panel_kakSuh = new javax.swing.JPanel();
        btn_kakSuh = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1000, 768));
        setLayout(new java.awt.CardLayout());

        panelMain.setBackground(new java.awt.Color(255, 255, 255));
        panelMain.setPreferredSize(new java.awt.Dimension(172, 610));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-edit-property-30.png"))); // NOI18N
        jLabel2.setText("Pencatatan");

        jLabel3.setBackground(new java.awt.Color(51, 255, 51));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Pedoman Pencatatan Progress");

        btn_Mulai.setText("Mulai Mencatat");
        btn_Mulai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MulaiActionPerformed(evt);
            }
        });

        jLabel4.setText("Sudah paham langkah-langkahnya? Mari mulai!");

        jLabel5.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 12)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-survey-50.png"))); // NOI18N
        jLabel5.setText("Lakukan Pendataan");

        jLabel6.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 12)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-input-50.png"))); // NOI18N
        jLabel6.setText("Lakukan input data");

        jLabel8.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 12)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-down-right-50.png"))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 12)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-validation-50.png"))); // NOI18N
        jLabel9.setText("Jangan lupa validasinya ya!");

        jLabel10.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 12)); // NOI18N
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-down-right-50.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(137, 137, 137))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addComponent(btn_Mulai)
                        .addGap(108, 108, 108))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jLabel8)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(319, Short.MAX_VALUE)
                    .addComponent(jLabel9)
                    .addGap(55, 55, 55)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addGap(30, 30, 30)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Mulai)
                    .addComponent(jLabel4))
                .addGap(14, 14, 14))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(335, Short.MAX_VALUE)
                    .addComponent(jLabel9)
                    .addGap(97, 97, 97)))
        );

        jLabel1.setBackground(new java.awt.Color(51, 255, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Pedoman Manajemen Adik Asuh");

        btn_manajemen.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        btn_manajemen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-book-100.png"))); // NOI18N
        btn_manajemen.setText("Buku Pedoman Manajemen Adik Asuh");
        btn_manajemen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_manajemenMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_manajemenMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_manajemenMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panel_manajemenLayout = new javax.swing.GroupLayout(panel_manajemen);
        panel_manajemen.setLayout(panel_manajemenLayout);
        panel_manajemenLayout.setHorizontalGroup(
            panel_manajemenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_manajemenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_manajemen, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE))
        );
        panel_manajemenLayout.setVerticalGroup(
            panel_manajemenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_manajemenLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_manajemen)
                .addGap(24, 24, 24))
        );

        btn_pencatatan.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        btn_pencatatan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-book-100 (3).png"))); // NOI18N
        btn_pencatatan.setText("Buku Pedoman Pencatatan Progress");
        btn_pencatatan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_pencatatanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_pencatatanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_pencatatanMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panel_pencatatanLayout = new javax.swing.GroupLayout(panel_pencatatan);
        panel_pencatatan.setLayout(panel_pencatatanLayout);
        panel_pencatatanLayout.setHorizontalGroup(
            panel_pencatatanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_pencatatan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel_pencatatanLayout.setVerticalGroup(
            panel_pencatatanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_pencatatanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_pencatatan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_kakSuh.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        btn_kakSuh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-book-100 (4).png"))); // NOI18N
        btn_kakSuh.setText("Buku Pedoman Kakak Asuh");
        btn_kakSuh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_kakSuhMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_kakSuhMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_kakSuhMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panel_kakSuhLayout = new javax.swing.GroupLayout(panel_kakSuh);
        panel_kakSuh.setLayout(panel_kakSuhLayout);
        panel_kakSuhLayout.setHorizontalGroup(
            panel_kakSuhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 429, Short.MAX_VALUE)
            .addGroup(panel_kakSuhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(btn_kakSuh, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE))
        );
        panel_kakSuhLayout.setVerticalGroup(
            panel_kakSuhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(panel_kakSuhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_kakSuhLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(btn_kakSuh, javax.swing.GroupLayout.PREFERRED_SIZE, 94, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panel_pencatatan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_manajemen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(panel_kakSuh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(53, 53, 53))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(panel_manajemen, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(panel_pencatatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(panel_kakSuh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 204));
        jLabel7.setText("Home > Pencatatan");

        javax.swing.GroupLayout panelMainLayout = new javax.swing.GroupLayout(panelMain);
        panelMain.setLayout(panelMainLayout);
        panelMainLayout.setHorizontalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(panelMainLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        panelMainLayout.setVerticalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(54, 54, 54)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(146, Short.MAX_VALUE))
        );

        add(panelMain, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void btn_MulaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MulaiActionPerformed
        // TODO add your handling code here:    
    FormProgress form = new FormProgress();
    form.setVisible(true);
    }//GEN-LAST:event_btn_MulaiActionPerformed

    private void btn_manajemenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_manajemenMouseClicked
        // TODO add your handling code here:
        BukuPedomanManajemen form = new BukuPedomanManajemen();
        form.setVisible(true);
    }//GEN-LAST:event_btn_manajemenMouseClicked

    private void btn_manajemenMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_manajemenMouseEntered
        // TODO add your handling code here:
        panel_manajemen.setBackground(new Color(0,153,0));
        panel_manajemen.setBackground(new Color(0,102,153));
    }//GEN-LAST:event_btn_manajemenMouseEntered

    private void btn_pencatatanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pencatatanMouseClicked
        // TODO add your handling code here:
        BukuPedomanProgress form = new BukuPedomanProgress();
        form.setVisible(true);
    }//GEN-LAST:event_btn_pencatatanMouseClicked

    private void btn_pencatatanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pencatatanMouseEntered
        // TODO add your handling code here:
        panel_pencatatan.setBackground(new Color(0,153,0));
        panel_pencatatan.setBackground(new Color(0,102,153));
    }//GEN-LAST:event_btn_pencatatanMouseEntered

    private void btn_pencatatanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pencatatanMouseExited
        // TODO add your handling code here:
        resetButtonColor(panel_pencatatan);

    }//GEN-LAST:event_btn_pencatatanMouseExited

    private void btn_kakSuhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_kakSuhMouseClicked
        // TODO add your handling code here:
    BukuPedomanKakSuh form = new BukuPedomanKakSuh();
    form.setVisible(true);
    }//GEN-LAST:event_btn_kakSuhMouseClicked

    private void btn_kakSuhMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_kakSuhMouseEntered
        // TODO add your handling code here:
        panel_kakSuh.setBackground(new Color(0,153,0));
        panel_kakSuh.setBackground(new Color(0,102,153));
    }//GEN-LAST:event_btn_kakSuhMouseEntered

    private void btn_kakSuhMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_kakSuhMouseExited
        // TODO add your handling code here:
         resetButtonColor(panel_kakSuh);

    }//GEN-LAST:event_btn_kakSuhMouseExited

    private void btn_manajemenMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_manajemenMouseExited
        // TODO add your handling code here:
        resetButtonColor(panel_manajemen);
    }//GEN-LAST:event_btn_manajemenMouseExited

    private void resetButtonColor(javax.swing.JPanel panel) {
        panel.setBackground(new Color(242, 242, 242)); // Warna latar belakang default
        panel.setForeground(new Color(255, 51, 0)); 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Mulai;
    private javax.swing.JLabel btn_kakSuh;
    private javax.swing.JLabel btn_manajemen;
    private javax.swing.JLabel btn_pencatatan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel panelMain;
    private javax.swing.JPanel panel_kakSuh;
    private javax.swing.JPanel panel_manajemen;
    private javax.swing.JPanel panel_pencatatan;
    // End of variables declaration//GEN-END:variables

    
}
