/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panelview;

import java.io.File;
import Laporan.CsvExportBuilder;
import Laporan.ExportBuilder;
import Laporan.PdfExportBuilder;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import javax.swing.JFileChooser;

/**
 *
 * @author raja
 */
public class menuLaporan extends javax.swing.JPanel {
    private String currentFilePath; // Variabel untuk menyimpan path file yang dibuka
    /**
     * Creates new form menuLaporan
     */
    public menuLaporan() {
        initComponents();
        //controller = new DisplayController(this);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        fileTextField = new javax.swing.JTextField();
        openButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        contentTextArea = new javax.swing.JTextArea();
        btnSimpanPerubahan = new javax.swing.JButton();
        btnConvert = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1000, 768));
        setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 768));

        fileTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileTextFieldActionPerformed(evt);
            }
        });

        openButton.setText("Open File");
        openButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openButtonActionPerformed(evt);
            }
        });

        contentTextArea.setColumns(20);
        contentTextArea.setRows(5);
        jScrollPane1.setViewportView(contentTextArea);

        btnSimpanPerubahan.setText("Simpan Perubahan");
        btnSimpanPerubahan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanPerubahanActionPerformed(evt);
            }
        });

        btnConvert.setText("Eksport");
        btnConvert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvertActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 204));
        jLabel7.setText("Home > Laporan");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnConvert)
                                .addGap(18, 18, 18)
                                .addComponent(btnSimpanPerubahan)))
                        .addGap(30, 30, 30))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(fileTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(openButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 535, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel7)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(68, 68, 68)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fileTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(openButton))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConvert)
                    .addComponent(btnSimpanPerubahan))
                .addContainerGap(182, Short.MAX_VALUE))
        );

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void fileTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fileTextFieldActionPerformed

    private void openButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openButtonActionPerformed
          if (jFileChooser1.showOpenDialog(this) == jFileChooser1.APPROVE_OPTION) {
            currentFilePath = jFileChooser1.getSelectedFile().toString();
            fileTextField.setText(currentFilePath);
            FileInputStream fis = null;
            try {
                fis = new FileInputStream(jFileChooser1.getSelectedFile());
                StringBuilder str = new StringBuilder();
                while (fis.available() > 0) {
                    str.append((char) fis.read());
                }
                contentTextArea.setText(str.toString());
                fis.close();
            } catch (FileNotFoundException ex) {
                System.err.println("File tidak ditemukan");
            } catch (IOException ex) {
                System.err.println("File gagal dibaca");
            }
        }
    }//GEN-LAST:event_openButtonActionPerformed

    private void btnSimpanPerubahanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanPerubahanActionPerformed
        String filePath = fileTextField.getText();
        try (FileOutputStream fos = new FileOutputStream(filePath);
             OutputStreamWriter osw = new OutputStreamWriter(fos);
             BufferedWriter writer = new BufferedWriter(osw)) {

            String textToSave = contentTextArea.getText();
            writer.write(textToSave);
            System.out.println("Perubahan berhasil disimpan.");
        } catch (IOException ex) {
            System.err.println("Gagal menyimpan perubahan: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnSimpanPerubahanActionPerformed

    private void btnConvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvertActionPerformed
         convertFile();
    }

    private void convertFile() {
        if (currentFilePath == null || currentFilePath.isEmpty()) {
            System.err.println("Tidak ada file yang dipilih untuk konversi.");
            return;
        }

        // Memilih lokasi file hasil
        JFileChooser saveChooser = new JFileChooser();
        int saveValue = saveChooser.showSaveDialog(this);

        if (saveValue == JFileChooser.APPROVE_OPTION) {
            File saveFile = saveChooser.getSelectedFile();
            String destinationPath = saveFile.getAbsolutePath();
            String extension = getFileExtension(saveFile);

            try {
                ExportBuilder builder = null;

                if ("pdf".equalsIgnoreCase(extension)) {
                    builder = new PdfExportBuilder();
                } else if ("csv".equalsIgnoreCase(extension)) {
                    builder = new CsvExportBuilder();
                } else {
                    throw new IllegalArgumentException("Format file tidak didukung: " + extension);
                }

                builder.setDataSource(currentFilePath);
                builder.setDestination(destinationPath);
                builder.convert();
                System.out.println("File berhasil dikonversi ke " + extension + " di " + destinationPath);
            } catch (IOException ex) {
                ex.printStackTrace();
            }
        }

    }//GEN-LAST:event_btnConvertActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConvert;
    private javax.swing.JButton btnSimpanPerubahan;
    private javax.swing.JTextArea contentTextArea;
    private javax.swing.JTextField fileTextField;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton openButton;
    // End of variables declaration//GEN-END:variables

    private String getFileExtension(File file) {
    String fileName = file.getName();
        int dotIndex = fileName.lastIndexOf('.');
        if (dotIndex == -1 || dotIndex == 0 || dotIndex == fileName.length() - 1) {
            return "";
        }
        return fileName.substring(dotIndex + 1).toLowerCase();
    }
}


