/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package applicationview;

import panelview.menuPencatatan;

/**
 *
 * @author raja
 */
public class BukuPedomanKakSuh extends javax.swing.JFrame {
    private menuPencatatan mo;
    /**
     * Creates new form BukuPedoman
     */
    public BukuPedomanKakSuh() {
        initComponents();
         mo = new menuPencatatan();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btn_kakSuh = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Buku pedoman kakak asuh adalah panduan komprehensif yang bertujuan untuk memberikan arahan dan bimbingan kepada kakak asuh dalam menjalankan peran mereka \ndengan efektif dan bertanggung jawab dalam mendampingi adik asuh mereka. Buku ini mencakup berbagai aspek penting, termasuk prinsip-prinsip dasar kakak asuh, strategi \nkomunikasi yang efektif, serta metode pendekatan yang mendukung perkembangan dan kesejahteraan adik asuh. \n\nTujuan utama dari buku pedoman ini adalah untuk memfasilitasi interaksi yang positif antara kakak asuh dan adik asuh, menciptakan lingkungan yang aman dan mendukung, serta \nmengembangkan hubungan yang berkelanjutan berdasarkan saling pengertian dan kepercayaan. Selain itu, buku pedoman ini juga menguraikan prosedur-prosedur penting dalam \nmenangani situasi yang mungkin timbul, seperti penanganan konflik atau cara mengatasi tantangan perkembangan adik asuh secara individual.\n\nDengan menyediakan panduan yang jelas dan mendalam, buku pedoman kakak asuh membantu kakak asuh untuk memahami tanggung jawab mereka secara lebih baik, serta \nmemberikan kerangka kerja yang berguna dalam membangun keterampilan komunikasi yang positif dan mengelola interaksi sehari-hari dengan adik asuh. Selain itu, buku ini juga \nberfungsi sebagai sumber referensi yang penting dalam merencanakan kegiatan pendampingan yang bervariasi dan relevan dengan kebutuhan adik asuh, \nsehingga dapat membantu dalam mencapai tujuan perkembangan dan kesejahteraan mereka secara optimal.");
        jScrollPane1.setViewportView(jTextArea1);

        btn_kakSuh.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        btn_kakSuh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-book-100 (4).png"))); // NOI18N
        btn_kakSuh.setText("Buku Pedoman Kakak Asuh");

        jButton1.setBackground(new java.awt.Color(0, 255, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Kembali");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(127, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn_kakSuh, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(235, 235, 235))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 903, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(44, 44, 44))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(btn_kakSuh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jButton1)
                .addGap(103, 103, 103))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        // Hide the current frame (assuming it's a JFrame)
        this.setVisible(false);

        // Make sure menuOrganize is visible (optional, if hidden previously)
        mo.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BukuPedomanKakSuh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BukuPedomanKakSuh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BukuPedomanKakSuh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BukuPedomanKakSuh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BukuPedomanKakSuh().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_kakSuh;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
