/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package applicationview;
import panelview.menuDashBoard;
import panelview.MenuAdikAsuh;
import panelview.menuLaporan;
import panelview.menuOrganize;
import java.awt.Color;
import panelview.menuKakakAsuh;
import panelview.MenuOrganizeTamu;
import panelview.menuPencatatan;

/**
 *
 * @author raja
 */
public class Home extends javax.swing.JFrame {

    // Variabel untuk menyimpan status tombol yang aktif
    private String activeButton = "";
    private boolean isPengajarTamu;

    
    /**
     * Creates new form pengajarTetap
     */
    public Home(boolean isPengajarTamu) {
        initComponents();
        this.isPengajarTamu = isPengajarTamu;

    }
    
    private void setActiveButton(String buttonName) {
        activeButton = buttonName;
        updateButtonColors();
    }
    
    private void updateButtonColors() {
        // Reset all button colors
        resetButtonColors();

        // Set color for the active button
        switch(activeButton) {
            case "dashboard":
                pn_main.setBackground(new Color(240,240,240));
                pn_lain.setBackground(new Color(0,102,153));
                break;
            case "kakakasuh":
                pn_main_kaksuh.setBackground(new Color(240,240,240));
                pn_lain_kaksuh1.setBackground(new Color(0,102,153));
                break;
            case "adikAsuh":
                pn_main_adsuh.setBackground(new Color(240,240,240));
                pn_lain_adsuh.setBackground(new Color(0,102,153));
                break;
            case "organize":
                pn_main_organize.setBackground(new Color(240,240,240));
                pn_lain_organize.setBackground(new Color(0,102,153));
                break;
            case "laporan":
                pn_main_laporan.setBackground(new Color(240,240,240));
                pn_lain_laporan.setBackground(new Color(0,102,153));
                break;
            case "pencatatan":
                pn_main_Pencatatan.setBackground(new Color(240,240,240));
                pn_lain_Pencatatan.setBackground(new Color(0,102,153));
                break;
        }
    }
    
    private void resetButtonColors() {
        pn_main.setBackground(new Color(0,255,255));
        pn_lain.setBackground(new Color(255,51,0));
        pn_main_kaksuh.setBackground(new Color(0,255,255));
        pn_lain_kaksuh1.setBackground(new Color(255,51,0));
        pn_main_adsuh.setBackground(new Color(0,255,255));
        pn_lain_adsuh.setBackground(new Color(255,51,0));
        pn_main_organize.setBackground(new Color(0,255,255));
        pn_lain_organize.setBackground(new Color(255,51,0));
        pn_main_laporan.setBackground(new Color(0,255,255));
        pn_lain_laporan.setBackground(new Color(255,51,0));
        pn_main_Pencatatan.setBackground(new Color(0,255,255));
        pn_lain_Pencatatan.setBackground(new Color(255,51,0));
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_kiri = new javax.swing.JPanel();
        pn_main = new javax.swing.JPanel();
        pn_lain = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btn_dashboard = new javax.swing.JLabel();
        pn_main_kaksuh = new javax.swing.JPanel();
        pn_lain_kaksuh1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btn_kakakasuh = new javax.swing.JLabel();
        pn_main_adsuh = new javax.swing.JPanel();
        pn_lain_adsuh = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btn_adsuh = new javax.swing.JLabel();
        pn_main_organize = new javax.swing.JPanel();
        pn_lain_organize = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btn_organize = new javax.swing.JLabel();
        pn_main_laporan = new javax.swing.JPanel();
        pn_lain_laporan = new javax.swing.JPanel();
        btn_laporan = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pn_main_Pencatatan = new javax.swing.JPanel();
        pn_lain_Pencatatan = new javax.swing.JPanel();
        btn_Pencatatan = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        pn_kanan = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btn_logout = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        pn_dasar = new javax.swing.JPanel();
        pn_utama = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pn_kiri.setBackground(new java.awt.Color(0, 0, 204));
        pn_kiri.setPreferredSize(new java.awt.Dimension(300, 678));

        pn_main.setBackground(new java.awt.Color(0, 255, 255));
        pn_main.setPreferredSize(new java.awt.Dimension(265, 58));

        pn_lain.setBackground(new java.awt.Color(255, 51, 0));

        javax.swing.GroupLayout pn_lainLayout = new javax.swing.GroupLayout(pn_lain);
        pn_lain.setLayout(pn_lainLayout);
        pn_lainLayout.setHorizontalGroup(
            pn_lainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );
        pn_lainLayout.setVerticalGroup(
            pn_lainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-dashboard-30 (1).png"))); // NOI18N
        jLabel3.setPreferredSize(new java.awt.Dimension(112, 70));

        btn_dashboard.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_dashboard.setText("Dashboard");
        btn_dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_dashboardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_dashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_dashboardMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_mainLayout = new javax.swing.GroupLayout(pn_main);
        pn_main.setLayout(pn_mainLayout);
        pn_mainLayout.setHorizontalGroup(
            pn_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_mainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pn_lain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_dashboard)
                .addContainerGap(109, Short.MAX_VALUE))
        );
        pn_mainLayout.setVerticalGroup(
            pn_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(btn_dashboard, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
            .addGroup(pn_mainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pn_lain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pn_main_kaksuh.setBackground(new java.awt.Color(0, 255, 255));
        pn_main_kaksuh.setPreferredSize(new java.awt.Dimension(280, 55));

        pn_lain_kaksuh1.setBackground(new java.awt.Color(255, 51, 0));
        pn_lain_kaksuh1.setPreferredSize(new java.awt.Dimension(12, 40));

        javax.swing.GroupLayout pn_lain_kaksuh1Layout = new javax.swing.GroupLayout(pn_lain_kaksuh1);
        pn_lain_kaksuh1.setLayout(pn_lain_kaksuh1Layout);
        pn_lain_kaksuh1Layout.setHorizontalGroup(
            pn_lain_kaksuh1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );
        pn_lain_kaksuh1Layout.setVerticalGroup(
            pn_lain_kaksuh1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-teaching-30.png"))); // NOI18N

        btn_kakakasuh.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_kakakasuh.setText("Penilaian");
        btn_kakakasuh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_kakakasuhMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_kakakasuhMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_kakakasuhMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_main_kaksuhLayout = new javax.swing.GroupLayout(pn_main_kaksuh);
        pn_main_kaksuh.setLayout(pn_main_kaksuhLayout);
        pn_main_kaksuhLayout.setHorizontalGroup(
            pn_main_kaksuhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_main_kaksuhLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_kakakasuh)
                .addContainerGap(117, Short.MAX_VALUE))
            .addGroup(pn_main_kaksuhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_main_kaksuhLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pn_lain_kaksuh1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(247, Short.MAX_VALUE)))
        );
        pn_main_kaksuhLayout.setVerticalGroup(
            pn_main_kaksuhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_main_kaksuhLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pn_main_kaksuhLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(btn_kakakasuh)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pn_main_kaksuhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_main_kaksuhLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pn_lain_kaksuh1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pn_main_adsuh.setBackground(new java.awt.Color(0, 255, 255));

        pn_lain_adsuh.setBackground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout pn_lain_adsuhLayout = new javax.swing.GroupLayout(pn_lain_adsuh);
        pn_lain_adsuh.setLayout(pn_lain_adsuhLayout);
        pn_lain_adsuhLayout.setHorizontalGroup(
            pn_lain_adsuhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 11, Short.MAX_VALUE)
        );
        pn_lain_adsuhLayout.setVerticalGroup(
            pn_lain_adsuhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 39, Short.MAX_VALUE)
        );

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-manage-30.png"))); // NOI18N

        btn_adsuh.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_adsuh.setText("Manajemen");
        btn_adsuh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_adsuhMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_adsuhMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_adsuhMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_main_adsuhLayout = new javax.swing.GroupLayout(pn_main_adsuh);
        pn_main_adsuh.setLayout(pn_main_adsuhLayout);
        pn_main_adsuhLayout.setHorizontalGroup(
            pn_main_adsuhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_main_adsuhLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_adsuh)
                .addContainerGap(99, Short.MAX_VALUE))
            .addGroup(pn_main_adsuhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_main_adsuhLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pn_lain_adsuh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(248, Short.MAX_VALUE)))
        );
        pn_main_adsuhLayout.setVerticalGroup(
            pn_main_adsuhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_main_adsuhLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(pn_main_adsuhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(btn_adsuh))
                .addContainerGap(11, Short.MAX_VALUE))
            .addGroup(pn_main_adsuhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_main_adsuhLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pn_lain_adsuh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pn_main_organize.setBackground(new java.awt.Color(0, 255, 255));

        pn_lain_organize.setBackground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout pn_lain_organizeLayout = new javax.swing.GroupLayout(pn_lain_organize);
        pn_lain_organize.setLayout(pn_lain_organizeLayout);
        pn_lain_organizeLayout.setHorizontalGroup(
            pn_lain_organizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );
        pn_lain_organizeLayout.setVerticalGroup(
            pn_lain_organizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-schedule-30.png"))); // NOI18N
        jLabel6.setText("jLabel6");

        btn_organize.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_organize.setText("Jadwal");
        btn_organize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_organizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_organizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_organizeMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_main_organizeLayout = new javax.swing.GroupLayout(pn_main_organize);
        pn_main_organize.setLayout(pn_main_organizeLayout);
        pn_main_organizeLayout.setHorizontalGroup(
            pn_main_organizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_main_organizeLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_organize)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pn_main_organizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_main_organizeLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pn_lain_organize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(247, Short.MAX_VALUE)))
        );
        pn_main_organizeLayout.setVerticalGroup(
            pn_main_organizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_main_organizeLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pn_main_organizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(btn_organize))
                .addContainerGap(8, Short.MAX_VALUE))
            .addGroup(pn_main_organizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_main_organizeLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pn_lain_organize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pn_main_laporan.setBackground(new java.awt.Color(0, 255, 255));

        pn_lain_laporan.setBackground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout pn_lain_laporanLayout = new javax.swing.GroupLayout(pn_lain_laporan);
        pn_lain_laporan.setLayout(pn_lain_laporanLayout);
        pn_lain_laporanLayout.setHorizontalGroup(
            pn_lain_laporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 11, Short.MAX_VALUE)
        );
        pn_lain_laporanLayout.setVerticalGroup(
            pn_lain_laporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );

        btn_laporan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_laporan.setText("Laporan");
        btn_laporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_laporanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_laporanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_laporanMouseExited(evt);
            }
        });

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-report-30.png"))); // NOI18N

        javax.swing.GroupLayout pn_main_laporanLayout = new javax.swing.GroupLayout(pn_main_laporan);
        pn_main_laporan.setLayout(pn_main_laporanLayout);
        pn_main_laporanLayout.setHorizontalGroup(
            pn_main_laporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_main_laporanLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel14)
                .addGap(27, 27, 27)
                .addComponent(btn_laporan)
                .addContainerGap(120, Short.MAX_VALUE))
            .addGroup(pn_main_laporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_main_laporanLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pn_lain_laporan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(248, Short.MAX_VALUE)))
        );
        pn_main_laporanLayout.setVerticalGroup(
            pn_main_laporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_main_laporanLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(pn_main_laporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14)
                    .addComponent(btn_laporan))
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(pn_main_laporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_main_laporanLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pn_lain_laporan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel2.setBackground(new java.awt.Color(51, 255, 51));

        jLabel1.setBackground(new java.awt.Color(51, 51, 255));
        jLabel1.setFont(new java.awt.Font("Snap ITC", 0, 3)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Aplikasi-removebg-preview__7_-removebg-preview.png"))); // NOI18N
        jLabel1.setText("APLIKASI PPAA");
        jLabel1.setMaximumSize(new java.awt.Dimension(500, 500));
        jLabel1.setPreferredSize(new java.awt.Dimension(100, 100));

        jLabel2.setBackground(new java.awt.Color(0, 0, 204));
        jLabel2.setFont(new java.awt.Font("Snap ITC", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 51));
        jLabel2.setText("APLIKASI PPAA");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pn_main_Pencatatan.setBackground(new java.awt.Color(0, 255, 255));

        pn_lain_Pencatatan.setBackground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout pn_lain_PencatatanLayout = new javax.swing.GroupLayout(pn_lain_Pencatatan);
        pn_lain_Pencatatan.setLayout(pn_lain_PencatatanLayout);
        pn_lain_PencatatanLayout.setHorizontalGroup(
            pn_lain_PencatatanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 11, Short.MAX_VALUE)
        );
        pn_lain_PencatatanLayout.setVerticalGroup(
            pn_lain_PencatatanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        btn_Pencatatan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_Pencatatan.setText("Pencatatan");
        btn_Pencatatan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_PencatatanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_PencatatanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_PencatatanMouseExited(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-edit-property-30.png"))); // NOI18N

        javax.swing.GroupLayout pn_main_PencatatanLayout = new javax.swing.GroupLayout(pn_main_Pencatatan);
        pn_main_Pencatatan.setLayout(pn_main_PencatatanLayout);
        pn_main_PencatatanLayout.setHorizontalGroup(
            pn_main_PencatatanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_main_PencatatanLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_Pencatatan)
                .addContainerGap(98, Short.MAX_VALUE))
            .addGroup(pn_main_PencatatanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_main_PencatatanLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pn_lain_Pencatatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(248, Short.MAX_VALUE)))
        );
        pn_main_PencatatanLayout.setVerticalGroup(
            pn_main_PencatatanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_main_PencatatanLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pn_main_PencatatanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(btn_Pencatatan))
                .addContainerGap(10, Short.MAX_VALUE))
            .addGroup(pn_main_PencatatanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_main_PencatatanLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pn_lain_Pencatatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Pengelolaan--------------------------------");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Evaluasi-------------------------------------");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("by Eurorea Wirata Raja Panjaitan");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/logosm-removebg-preview (2).png"))); // NOI18N

        javax.swing.GroupLayout pn_kiriLayout = new javax.swing.GroupLayout(pn_kiri);
        pn_kiri.setLayout(pn_kiriLayout);
        pn_kiriLayout.setHorizontalGroup(
            pn_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pn_kiriLayout.createSequentialGroup()
                .addGroup(pn_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_kiriLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(pn_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pn_main_adsuh, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pn_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(pn_main_laporan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pn_main_kaksuh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                                .addComponent(pn_main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pn_main_organize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pn_main_Pencatatan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(pn_kiriLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pn_kiriLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jLabel11)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        pn_kiriLayout.setVerticalGroup(
            pn_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_kiriLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(pn_main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(pn_main_adsuh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pn_main_Pencatatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pn_main_organize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(pn_main_kaksuh, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pn_main_laporan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addContainerGap(166, Short.MAX_VALUE))
        );

        getContentPane().add(pn_kiri, java.awt.BorderLayout.LINE_START);

        pn_kanan.setBackground(new java.awt.Color(255, 255, 255));
        pn_kanan.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(105, 207, 154));
        jPanel1.setForeground(new java.awt.Color(28, 191, 76));
        jPanel1.setPreferredSize(new java.awt.Dimension(1266, 70));

        btn_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-logout-50 (1).png"))); // NOI18N
        btn_logout.setText("jLabel7");
        btn_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_logoutMouseClicked(evt);
            }
        });

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-info-50.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(1267, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(btn_logout))
                .addGap(23, 23, 23))
        );

        pn_kanan.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        pn_dasar.setBackground(new java.awt.Color(204, 204, 204));

        pn_utama.setBackground(new java.awt.Color(255, 255, 255));
        pn_utama.setPreferredSize(new java.awt.Dimension(1000, 768));
        pn_utama.setLayout(new java.awt.BorderLayout());

        jLabel15.setFont(new java.awt.Font("SimSun", 1, 48)); // NOI18N
        jLabel15.setText("         SELAMAT DATANG DI APLIKASI PPAA");
        pn_utama.add(jLabel15, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout pn_dasarLayout = new javax.swing.GroupLayout(pn_dasar);
        pn_dasar.setLayout(pn_dasarLayout);
        pn_dasarLayout.setHorizontalGroup(
            pn_dasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_dasarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(pn_utama, javax.swing.GroupLayout.PREFERRED_SIZE, 1200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(166, Short.MAX_VALUE))
        );
        pn_dasarLayout.setVerticalGroup(
            pn_dasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_dasarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(pn_utama, javax.swing.GroupLayout.DEFAULT_SIZE, 789, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        pn_kanan.add(pn_dasar, java.awt.BorderLayout.CENTER);

        getContentPane().add(pn_kanan, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dashboardMouseEntered
        // TODO add your handling code here:
        pn_main.setBackground(new Color(250,250,250));
        pn_lain.setBackground(new Color(0,102,153));
    }//GEN-LAST:event_btn_dashboardMouseEntered

    private void btn_dashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dashboardMouseExited
        // TODO add your handling code here:
        if (!"dashboard".equals(activeButton)) {
            pn_main.setBackground(new Color(0,255,255));
            pn_lain.setBackground(new Color(255,51,0));
        }
    }//GEN-LAST:event_btn_dashboardMouseExited

    private void btn_dashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
        // TODO add your handling code here:
        if (!"dashboard".equals(activeButton)) {
            pn_main.setBackground(new Color(0,153,0));
            pn_lain.setBackground(new Color(0,102,153));
        }
    }//GEN-LAST:event_jLabel4MouseEntered

    private void btn_dashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dashboardMouseClicked
        // TODO add your handling code here:
        setActiveButton("dashboard");
        pn_utama.removeAll();
        pn_utama.add(new menuDashBoard());
        pn_utama.repaint();
        pn_utama.revalidate();
    }//GEN-LAST:event_btn_dashboardMouseClicked

    private void btn_kakakasuhMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_kakakasuhMouseEntered
        // TODO add your handling code here:
         if (!"kakakasuh".equals(activeButton)) {
            pn_main_kaksuh.setBackground(new Color(0,153,0));
            pn_lain_kaksuh1.setBackground(new Color(0,102,153));
        }
    }//GEN-LAST:event_btn_kakakasuhMouseEntered

    private void btn_kakakasuhMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_kakakasuhMouseExited
        // TODO add your handling code here:
        if (!"kakakasuh".equals(activeButton)) {
            pn_main_kaksuh.setBackground(new Color(0,255,255));
            pn_lain_kaksuh1.setBackground(new Color(255,51,0));
        }
        
    }//GEN-LAST:event_btn_kakakasuhMouseExited

    private void btn_adsuhMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_adsuhMouseEntered
        // TODO add your handling code here:
        if (!"adikAsuh".equals(activeButton)) {
            pn_main_adsuh.setBackground(new Color(0,153,0));
            pn_lain_adsuh.setBackground(new Color(0,102,153));
        }
    }//GEN-LAST:event_btn_adsuhMouseEntered

    private void btn_adsuhMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_adsuhMouseExited
        // TODO add your handling code here:
         if (!"adikAsuh".equals(activeButton)) {
            pn_main_adsuh.setBackground(new Color(0,255,255));
            pn_lain_adsuh.setBackground(new Color(255,51,0));
        }
    }//GEN-LAST:event_btn_adsuhMouseExited

    private void btn_organizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_organizeMouseExited
        // TODO add your handling code here:
       if (!"organize".equals(activeButton)) {
            pn_main_organize.setBackground(new Color(0,255,255));
            pn_lain_organize.setBackground(new Color(255,51,0));
        }
    }//GEN-LAST:event_btn_organizeMouseExited

    private void btn_organizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_organizeMouseEntered
        // TODO add your handling code here:
        if (!"organize".equals(activeButton)) {
            pn_main_organize.setBackground(new Color(0,153,0));
            pn_lain_organize.setBackground(new Color(0,102,153));
        }
    }//GEN-LAST:event_btn_organizeMouseEntered

    private void btn_adsuhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_adsuhMouseClicked
        // TODO add your handling code here:
        setActiveButton("adikAsuh");
        pn_utama.removeAll();
        pn_utama.add(new MenuAdikAsuh());
        pn_utama.repaint();
        pn_utama.revalidate();
    }//GEN-LAST:event_btn_adsuhMouseClicked

    private void btn_organizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_organizeMouseClicked
        // TODO add your handling code here:
        if (isPengajarTamu) {
            setActiveButton("organize");
            pn_utama.removeAll();
            pn_utama.add(new MenuOrganizeTamu()); // Menu untuk pengajar tamu
            pn_utama.repaint();
            pn_utama.revalidate();
        } else {
            setActiveButton("organize");
            pn_utama.removeAll();
            pn_utama.add(new menuOrganize()); // Menu untuk pengajar reguler
            pn_utama.repaint();
            pn_utama.revalidate();
        }
    }//GEN-LAST:event_btn_organizeMouseClicked

    private void btn_laporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_laporanMouseClicked
        // TODO add your handling code here:
        setActiveButton("laporan");
        pn_utama.removeAll();
        pn_utama.add(new menuLaporan());
        pn_utama.repaint();
        pn_utama.revalidate();
    }//GEN-LAST:event_btn_laporanMouseClicked

    private void btn_laporanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_laporanMouseEntered
        // TODO add your handling code here:
         if (!"laporan".equals(activeButton)) {
            pn_main_laporan.setBackground(new Color(0,153,0));
            pn_lain_laporan.setBackground(new Color(0,102,153));
        }
    }//GEN-LAST:event_btn_laporanMouseEntered

    private void btn_laporanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_laporanMouseExited
        // TODO add your handling code here:
          if (!"laporan".equals(activeButton)) {
            pn_main_laporan.setBackground(new Color(0,255,255));
            pn_lain_laporan.setBackground(new Color(255,51,0));
        }
    }//GEN-LAST:event_btn_laporanMouseExited

    private void btn_kakakasuhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_kakakasuhMouseClicked
        // TODO add your handling code here:
        setActiveButton("kakakasuh");
        pn_utama.removeAll();
        pn_utama.add(new menuKakakAsuh());
        pn_utama.repaint();
        pn_utama.revalidate();
    }//GEN-LAST:event_btn_kakakasuhMouseClicked

    private void btn_PencatatanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_PencatatanMouseClicked
        // TODO add your handling code here:
         setActiveButton("pencatatan");
        pn_utama.removeAll();
        pn_utama.add(new menuPencatatan());
        pn_utama.repaint();
        pn_utama.revalidate();  
    }//GEN-LAST:event_btn_PencatatanMouseClicked

    private void btn_PencatatanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_PencatatanMouseEntered
        // TODO add your handling code here:
        if (!"pencatatan".equals(activeButton)) {
            pn_main_Pencatatan.setBackground(new Color(0,153,0));
            pn_lain_Pencatatan.setBackground(new Color(0,102,153));
        }
    }//GEN-LAST:event_btn_PencatatanMouseEntered

    private void btn_PencatatanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_PencatatanMouseExited
        // TODO add your handling code here:
        if (!"pencatatan".equals(activeButton)) {
            pn_main_Pencatatan.setBackground(new Color(0,255,255));
            pn_lain_Pencatatan.setBackground(new Color(255,51,0));
        }
    }//GEN-LAST:event_btn_PencatatanMouseExited

    private void btn_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logoutMouseClicked
        // TODO add your handling code here:
        Open openFrame = new Open();
        openFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_logoutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_Pencatatan;
    private javax.swing.JLabel btn_adsuh;
    private javax.swing.JLabel btn_dashboard;
    private javax.swing.JLabel btn_kakakasuh;
    private javax.swing.JLabel btn_laporan;
    private javax.swing.JLabel btn_logout;
    private javax.swing.JLabel btn_organize;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel pn_dasar;
    private javax.swing.JPanel pn_kanan;
    private javax.swing.JPanel pn_kiri;
    private javax.swing.JPanel pn_lain;
    private javax.swing.JPanel pn_lain_Pencatatan;
    private javax.swing.JPanel pn_lain_adsuh;
    private javax.swing.JPanel pn_lain_kaksuh1;
    private javax.swing.JPanel pn_lain_laporan;
    private javax.swing.JPanel pn_lain_organize;
    private javax.swing.JPanel pn_main;
    private javax.swing.JPanel pn_main_Pencatatan;
    private javax.swing.JPanel pn_main_adsuh;
    private javax.swing.JPanel pn_main_kaksuh;
    private javax.swing.JPanel pn_main_laporan;
    private javax.swing.JPanel pn_main_organize;
    private javax.swing.JPanel pn_utama;
    // End of variables declaration//GEN-END:variables
}
