/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package applicationview;

import javax.swing.JFrame;
import login.GuestLoginFactory;
import login.RegulerLoginFactory;

/**
 *
 * @author raja
 */
public class Open extends javax.swing.JFrame {

    public Open() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_guest = new javax.swing.JButton();
        btn_reguler = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("WELCOME");
        setPreferredSize(new java.awt.Dimension(800, 500));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 0));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/logosm-removebg-preview.png"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Snap ITC", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 51));
        jLabel7.setText("APLIKASI PPAA");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addContainerGap(162, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 400, 510);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Selamat Datang!");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(470, 70, 280, 48);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("Ingin login sebagai siapa?");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(470, 170, 300, 32);

        btn_guest.setBackground(new java.awt.Color(0, 102, 102));
        btn_guest.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_guest.setForeground(new java.awt.Color(255, 255, 255));
        btn_guest.setText("Pengajar Tamu");
        btn_guest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guestActionPerformed(evt);
            }
        });
        jPanel1.add(btn_guest);
        btn_guest.setBounds(630, 250, 140, 27);

        btn_reguler.setBackground(new java.awt.Color(0, 102, 102));
        btn_reguler.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_reguler.setForeground(new java.awt.Color(255, 255, 255));
        btn_reguler.setText("Pengajar Reguler");
        btn_reguler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regulerActionPerformed(evt);
            }
        });
        jPanel1.add(btn_reguler);
        btn_reguler.setBounds(440, 250, 160, 27);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_guestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guestActionPerformed
        GuestLoginFactory guestLoginFactory = new GuestLoginFactory();
        JFrame guestLogin = guestLoginFactory.createLogin();
        guestLogin.setVisible(true);
        guestLogin.pack();
        guestLogin.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btn_guestActionPerformed

    private void btn_regulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_regulerActionPerformed
        // TODO add your handling code here:
        RegulerLoginFactory regulerLoginFactory = new RegulerLoginFactory();
        JFrame regulerLogin = regulerLoginFactory.createLogin();
        regulerLogin.setVisible(true);
        regulerLogin.pack();
        regulerLogin.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btn_regulerActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_guest;
    private javax.swing.JButton btn_reguler;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
