/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package applicationview;

import applicationserverdb.DBConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.sql.SQLException;


/**
 *
 * @author raja
 */
public class SignUpReguler extends javax.swing.JFrame {

        Connection con = null;
        PreparedStatement pst = null;
        ResultSet rs = null;
        
        private LoginReguler loginreg;
        
    public SignUpReguler(LoginReguler loginreg) {
        initComponents();
        con = DBConnection.connectDB();
        this.loginreg = loginreg; // Inisialisasi referensi frame Login

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        passwordSignUPField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        namaTextField = new javax.swing.JTextField();
        usernameSignUpField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        buttonSignUP = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SIGN UP PENGAJAR REGULER");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 0));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/logosm-removebg-preview.png"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Snap ITC", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 51));
        jLabel7.setText("APLIKASI PPAA");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addContainerGap(162, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 400, 510);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("SIGN UP REGULER");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(450, 40, 330, 48);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Password");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(470, 230, 70, 20);
        jPanel1.add(passwordSignUPField);
        passwordSignUPField.setBounds(470, 260, 270, 22);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Nama");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(470, 110, 50, 20);
        jPanel1.add(namaTextField);
        namaTextField.setBounds(470, 140, 270, 22);
        jPanel1.add(usernameSignUpField);
        usernameSignUpField.setBounds(470, 200, 270, 22);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Username");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(470, 170, 80, 20);

        buttonSignUP.setBackground(new java.awt.Color(0, 102, 102));
        buttonSignUP.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonSignUP.setForeground(new java.awt.Color(255, 255, 255));
        buttonSignUP.setText("Sign Up");
        buttonSignUP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSignUPActionPerformed(evt);
            }
        });
        jPanel1.add(buttonSignUP);
        buttonSignUP.setBounds(470, 310, 90, 27);

        jLabel5.setText("I have an account");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(470, 360, 100, 16);

        jButton2.setText("Login");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(580, 360, 75, 23);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        loginreg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void buttonSignUPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSignUPActionPerformed
        // TODO add your handling code here:
         // Tombol Sign Up
        String nama = namaTextField.getText().trim();
        String username = usernameSignUpField.getText().trim();
        String password = passwordSignUPField.getText().trim();

        // Validasi input
        if (nama.isEmpty() || username.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please fill in all fields!");
            return;
        }

        // Validasi nama hanya mengandung huruf
        if (!nama.matches("[a-zA-Z\\s]+")) {
            JOptionPane.showMessageDialog(null, "Nama harus diisi dengan huruf saja!");
            return;
        }

        try {
            // Query untuk memasukkan data pengguna baru ke dalam database
            String sql = "INSERT INTO RegulerTeacher (nama, username, password) VALUES (?, ?, ?);";
            pst = con.prepareStatement(sql);
            pst.setString(1, nama);
            pst.setString(2, username);
            pst.setString(3, password);

            // Jalankan query
            pst.executeUpdate();

            JOptionPane.showMessageDialog(null, "Registration Successful!");
            this.dispose();
            loginreg.setVisible(true); // Tampilkan frame login setelah sign up berhasil
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Registration failed: " + e.getMessage());
        }
    }//GEN-LAST:event_buttonSignUPActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonSignUP;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField namaTextField;
    private javax.swing.JTextField passwordSignUPField;
    private javax.swing.JTextField usernameSignUpField;
    // End of variables declaration//GEN-END:variables
}
